services:
  database:
    image: "postgres:alpine3.23" # Buscar, em Docker Hub, uma imagem do SGBD escolhido.
    ports:
      - "5432:5432" # Inserir a porta do SGBD escolhido.
    environment:
      POSTGRES_PASSWORD: "local_password" # Inserir qual ser√° a senha de acesso do SGBD escolhido.
