services:
  database:
    image: "postgres:16.11-alpine3.23" # Buscar, em Docker Hub, uma imagem do SGBD escolhido.
    ports:
      - "5432:5432" # Inserir a porta do SGBD escolhido.
    env_file:
      - ../.env.development
